displayThisText(typeof(undefined))
displayThisText(typeof(true))
displayThisText(typeof(42))
displayThisText(typeof(123n))
displayThisText(typeof (f))
displayThisText(typeof Symbol())
displayThisText(typeof(displayThisText))
